export const DIET_RESTRICTIONS = [
  "Vegan",
  "Vegetarian",
  "Lacto-vegetarian",
  "Ovo-vegetarian",
  "Lacto-ovo vegetarian",
  "Pescatarian",
  "Pollotarian",
  "Flexitarian",
  "Carnivore",
  "Fruitarian",
  "Raw vegan",
  "Raw vegetarian",
  "Gluten-free",
  "Wheat-free",
  "Dairy-free",
  "Lactose-free",
  "Casein-free",
  "Egg-free",
  "Soy-free",
  "Nut-free",
  "Peanut-free",
  "Tree nut–free",
  "Shellfish-free",
  "Fish-free",
  "Sesame-free",
  "Mustard-free",
  "Celery-free",
  "Lupin-free",
  "Sulfite-free",
  "Corn-free",
  "Yeast-free",
  "Sugar-free",
  "No added sugar",
  "Low-sugar",
  "Keto",
  "Low-carb",
  "High-protein",
  "High-fat",
  "Low-fat",
  "Low-cholesterol",
  "Low-sodium",
  "Salt-free",
  "Low-histamine",
  "Low-FODMAP",
  "Low-oxalate",
  "Low-purine",
  "Low-iodine",
  "Renal diet",
  "Diabetic diet",
  "Cardiac diet",
  "Anti-inflammatory",
  "Elimination diet",
  "Autoimmune protocol (AIP)",
  "Paleo",
  "Whole30",
  "Mediterranean",
  "DASH",
  "MIND",
  "Alkaline diet",
  "Macrobiotic",
  "Ayurvedic",
  "Halal",
  "Kosher",
  "Jain",
  "Buddhist vegetarian",
  "Seventh-day Adventist diet",
  "Sattvic",
  "Low-calorie",
  "Calorie-restricted",
  "Intermittent fasting",
  "Time-restricted eating",
  "OMAD",
  "Liquid diet",
  "Clear liquid diet",
  "BRAT diet",
  "Bland diet",
  "Soft food diet",
  "Mechanical soft diet",
  "Pureed diet",
  "Tube feeding (enteral)",
  "Parenteral nutrition",
  "Low-residue",
  "High-fiber",
  "Low-fiber",
  "Lectin-free",
  "Nightshade-free",
  "Caffeine-free",
  "Alcohol-free",
  "MSG-free",
  "Preservative-free",
  "Additive-free",
  "Organic-only",
  "Non-GMO",
  "Grass-fed only",
  "Pasture-raised only",
  "Wild-caught only",
  "Local-only (locavore)",
  "Seasonal-only",
  "Ethical omnivore",
  "Zero-waste diet",
];

export enum EDietRestriction {
  DIET_RESTRICTIONS,
}

export type Tag = {
  reviewId: string;
  restaurantId: string;
  label: EDietRestriction;
};
